services:
  database:
    image: postgres:17
    container_name: chess-db-indexing-database
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  otel-lgtm:
    image: grafana/otel-lgtm:0.8.4
    container_name: chess-db-indexing-otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
